apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eg-esign-pdb
  labels:
    app: eg-esign
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: eg-esign
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: minio-pdb
  labels:
    app: minio
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: minio
