apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eg-esign-staging
resources:
  - ../../base
images:
  - name: epicregistry.azurecr.io/epic-group-software/eg-esign
    newTag: staging
patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
