apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eg-esign-prod
resources:
  - ../../base
images:
  - name: epicregistry.azurecr.io/davinci-technology/eg-esign
    newTag: prod
patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
