apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.componentLabels" (dict "component" "app" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.service.app.type }}
  selector:
    {{- include "app.componentSelectorLabels" (dict "component" "app" "context" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.app.port }}
      targetPort: http
